liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
#    loaders:
#        default:
#            filesystem:
#                data_root: '%kernel.project_dir%/public/'
    # define your filter sets under this option
    filter_sets:

        # an example thumbnail transformation definition
        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        fileManager_thumbnail:

            # set your image quality defaults
            jpeg_quality:          100
            png_compression_level: 8

            # setup the filter steps to apply for this transformation
            filters:

                # auto rotate the image using EXIF metadata
                auto_rotate: ~

                # strip the image of all metadata
                strip: ~

                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [128, 128]
                    mode:          outbound
                    allow_upscale: true

                # create border by placing image on larger black background
#                background:
#                    size:     [256, 256]
#                    position: center
#                    color:    '#fff'

        product_mainpic_thumbnail:

            # set your image quality defaults
            jpeg_quality:          100
            png_compression_level: 8

            # setup the filter steps to apply for this transformation
            filters:

                # auto rotate the image using EXIF metadata
                auto_rotate: ~

                # strip the image of all metadata
                strip: ~

                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [1026, 1270]
                    mode:          outbound
                    allow_upscale: true

                # create border by placing image on larger black background
#                background:
#                    size:     [256, 256]
#                    position: center
#                    color:    '#fff'

        product_saleprops_thumbnail:

            # set your image quality defaults
            jpeg_quality:          100
            png_compression_level: 8

            # setup the filter steps to apply for this transformation
            filters:

                # auto rotate the image using EXIF metadata
                auto_rotate: ~

                # strip the image of all metadata
                strip: ~

                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [40, 40]
                    mode:          outbound
                    allow_upscale: true

                # create border by placing image on larger black background
#                background:
#                    size:     [25, 25]
#                    position: center
#                    color:    '#888888'

        product_grid_img_thumbnail:

            # set your image quality defaults
            jpeg_quality:          100
            png_compression_level: 8

            # setup the filter steps to apply for this transformation
            filters:

                # auto rotate the image using EXIF metadata
                auto_rotate: ~

                # strip the image of all metadata
                strip: ~

                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [540, 668]
                    mode:          outbound
                    allow_upscale: true


        bolg_content_thumbnail:

            # set your image quality defaults
            jpeg_quality:          100
            png_compression_level: 8

            # setup the filter steps to apply for this transformation
            filters:

                # auto rotate the image using EXIF metadata
                auto_rotate: ~

                # strip the image of all metadata
                strip: ~

                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [800, 400]
                    mode:          outbound
                    allow_upscale: true

        content_list_product_thumbnail:

            # set your image quality defaults
            jpeg_quality:          100
            png_compression_level: 8

            # setup the filter steps to apply for this transformation
            filters:

                # auto rotate the image using EXIF metadata
                auto_rotate: ~

                # strip the image of all metadata
                strip: ~

                # scale and square the image to the given dimensions
                thumbnail:
                    size:          [90, 110]
                    mode:          outbound
                    allow_upscale: true